require('dotenv/config')

const {
  SIZE_GENERATION,
  MAX_GENERATIONS,
  MAX_GENERATE_CHROMOSOME_SIZE,
  MAX_CHROMOSOME_SIZE,
  EXPECTED_EVALUATION,
  CROSSOVER_RATE,
  MUTATION_RATE,
  MUTATION_LEVEL,
  CROSSOVER_LEVEL
} = process.env

module.exports = () => {
  return {
    SIZE_GENERATION: parseInt(SIZE_GENERATION),
    MAX_GENERATIONS: parseInt(MAX_GENERATIONS),
    MAX_GENERATE_CHROMOSOME_SIZE: parseInt(MAX_GENERATE_CHROMOSOME_SIZE),
    MAX_CHROMOSOME_SIZE: parseInt(MAX_CHROMOSOME_SIZE),
    EXPECTED_EVALUATION: parseInt(EXPECTED_EVALUATION),
    CROSSOVER_RATE: parseInt(CROSSOVER_RATE),
    MUTATION_RATE: parseInt(MUTATION_RATE),
    MUTATION_LEVEL: parseInt(MUTATION_LEVEL),
    CROSSOVER_LEVEL: parseInt(CROSSOVER_LEVEL)
  }
}